### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [joshuacurl/tc359-skill14#1]
When I submit the form, I'm getting an `Internal Server Error` unfortunately. You should be able to see what's going on in the console with `heroku logs`.

**Comment by joshuacurl** [comment]
Looks like I had the wrong country code for the UK! It should be okay now.

**Comment by chrisvfritz** [comment]
:+1: Much better! I would clean up [these `puts` statements](https://github.com/joshuacurl/tc359-skill14/blob/master/app.rb#L12-L13), but other than that, the code's looking very good.
